// Parses the budget identifiers the browser sends on every paid API call:
// `X-Session-Id` (one browser tab, kept in sessionStorage) and `X-Run-Id`
// (one search including its later "next 5" batches). Both are UUID v4 values
// generated by the browser; they are correlation ids, not authentication.
import { z } from "zod";
import type { BudgetRequestContext } from "./ledger.ts";

export const SESSION_ID_HEADER = "X-Session-Id";
export const RUN_ID_HEADER = "X-Run-Id";

const uuidV4 = z
  .string()
  .regex(
    /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
    {
      message: "UUID v4 形式ではありません。",
    },
  );

export const budgetHeadersSchema = z.object({
  sessionId: uuidV4,
  runId: uuidV4,
});

export type ParsedBudgetContext =
  | { ok: true; context: BudgetRequestContext }
  | { ok: false; message: string };

export function parseBudgetContext(headers: Headers): ParsedBudgetContext {
  const parsed = budgetHeadersSchema.safeParse({
    sessionId: headers.get(SESSION_ID_HEADER) ?? "",
    runId: headers.get(RUN_ID_HEADER) ?? "",
  });
  if (parsed.success)
    return {
      ok: true,
      context: {
        sessionId: parsed.data.sessionId.toLowerCase(),
        runId: parsed.data.runId.toLowerCase(),
      },
    };
  const issues = parsed.error.issues.map((issue) => {
    const header =
      issue.path[0] === "sessionId" ? SESSION_ID_HEADER : RUN_ID_HEADER;
    return `${header}: ${issue.message}`;
  });
  return { ok: false, message: `入力が不正です: ${issues.join("; ")}` };
}
